### ISSUE TITLE
Error during build: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by adam-nygate** [windicss/nuxt-windicss-module#16]
When running `npm run dev`, I get this error after nuxt logs `✔ Nuxt files generated`:

```
ERROR  Cannot convert undefined or null to object                                                          10:03:51

  at Function.entries (<anonymous>)
  at generateStaticStyle (node_modules/windicss/lib/index.js:7542:34)
  at extract (node_modules/windicss/lib/index.js:7559:16)
  at Processor.extract (node_modules/windicss/lib/index.js:8099:16)
  at _gStyle (node_modules/windicss/lib/index.js:8143:32)
  at node_modules/windicss/lib/index.js:8198:25
  at Array.forEach (<anonymous>)
  at Processor.interpret (node_modules/windicss/lib/index.js:8191:13)
  at Object.generateCSS (node_modules/@windicss/plugin-utils/dist/index.js:44609:32)
  at async safeStartService (node_modules/windicss-webpack-plugin/dist/plugin.js:194:78)
  at async node_modules/windicss-webpack-plugin/dist/plugin.js:207:13
```

Any idea on how to fix?

**Comment by productfrontenddeveloper** [comment]
Hi @adam-nygate,
Please more information add.
May be good for checking if you add the library names and the nuxt version you are using. Etc add
```
"nuxt": "2.15.2",
"nuxt-windicss": "^0.3.1",
``` 
nuxt.config setting
tailwindcss...

**Comment by adam-nygate** [comment]
As requested...

package.json:
```
"nuxt": "^2.15.3",
...
"nuxt-windicss": "^0.3.1",
```

nuxt.config.js:
```
export default {
  srcDir: 'src/',
  target: 'static',
  css: ['./src/static/css/main.css'],
  components: true,
  render: {
    static: {
      maxAge: 60 * 60 * 24 * 365 * 1000
    }
  },
  build: {
    // Fixes Safari infinite hot-reload bug
    devMiddleware: {
      headers: {
        'Cache-Control': 'no-store',
        Vary: '*'
      }
    }
  },
  generate: {
    fallback: '404.html',
    async routes() { ... },
    exclude: [ ... ]
  },
  plugins: [ ... ],
  buildModules: [
    // https://go.nuxtjs.dev/typescript
    '@nuxt/typescript-build',
    // https://github.com/windicss/nuxt-windicss-module
    'nuxt-windicss',
    // https://github.com/nuxt-community/moment-module
    '@nuxtjs/moment',
    // https://github.com/nuxt-community/fontawesome-module
    '@nuxtjs/fontawesome'
  ],
  modules: [
    // https://go.nuxtjs.dev/axios
    '@nuxtjs/axios',
    // https://go.nuxtjs.dev/content
    '@nuxt/content',
    // https://auth.nuxtjs.org/
    '@nuxtjs/auth-next',
    // https://github.com/dansmaculotte/nuxt-segment
    '@dansmaculotte/nuxt-segment',
    // https://github.com/nuxt-community/apollo-module
    '@nuxtjs/apollo',
    // https://sitemap.nuxtjs.org/guide/setup
    '@nuxtjs/sitemap',
    // https://github.com/nuxt-community/robots-module
    '@nuxtjs/robots'
  ],
};
```

tailwind.config.js:
```
module.exports = {
  darkMode: 'class', // or 'media' or 'class'
  theme: {
    fontFamily: {
      montserrat: ['Montserrat', 'sans-serif']
    },
    extend: {
      typography: (theme) => ({
        dark: {
          css: {
            color: theme('colors.gray.300'),
            a: {
              color: theme('colors.brand'),
              '&:hover': {
                color: theme('colors.red.500')
              }
            },
            h1: {
              color: theme('colors.gray.300')
            },
            h2: {
              color: theme('colors.gray.300')
            },
            h3: {
              color: theme('colors.gray.300')
            },
            h4: {
              color: theme('colors.gray.300')
            },
            h5: {
              color: theme('colors.gray.300')
            },
            h6: {
              'text-align': 'center',
              color: theme('colors.gray.300')
            },
            strong: {
              color: theme('colors.gray.300')
            },
            code: {
              color: theme('colors.gray.300')
            },
            figcaption: {
              color: theme('colors.gray.500')
            },
            em: {
              color: theme('colors.brand')
            },

            // Centers images
            img: {
              margin: theme('margin.auto'),
              display: 'block'
            },

            // Removes quotes
            'blockquote p:first-of-type::before': { content: 'none' },
            'blockquote p:first-of-type::after': { content: 'none' },
            'code::before': { content: 'none' },
            'code::after': { content: 'none' }
          }
        }
      }),

      spacing: {
        bountycard: '16.25rem',
        'card-header-w': '13.125rem',
        'card-header-h': '3.0625rem',
        'bounty-icon-w': '2.0625rem',
        'bounty-header-height': '3.0625'
      },
      // Adds brand and complimentary colors
      colors: {
        'brand-light': '#ffd7d0',
        brand: '#ef5a4d',
        'brand-dark': '#723029',

        'cta-light': '#dbfcea',
        cta: '#4defab',
        'cta-dark': '#2f7052',

        'info-light': '#e4f1f6',
        info: '#90c6d9',
        'info-dark': '#475e67',

        'warning-light': '#fff0cd',
        warning: '#fec526',
        'warning-dark': '#785d1d',

        'success-light': '#e3f5d2',
        success: '#82d647',
        'success-dark': '#426528',

        'danger-light': '#ffd4cd',
        danger: '#fc3d46',
        'danger-dark': '#782725',

        'gray-blue': '#31363F',
        'pill-gray': '#555555',
        'alert-green': '#00c642',
        'settings-gray': '#222222',
        'darker-gray': '#141414',
        'yellow-activity': '#FFD501',
        'orange-activity': '#FF8800',
        'discord-blue': '#7289DA',
        'bright-green': '#2ea44f',
        'dark-green': '#158B36',
        bountycard: {
          DEFAULT: '#161d1a'
        }
      }
    }
  },
  plugins: [
    require('windicss/plugin/typography'),
    require('windicss/plugin/forms')
  ]
};
```

**Comment by adam-nygate** [comment]
Console logging `utility` in `generateStaticStyle` returns:
```
{                                                                                                           10:08:57
  display: 'table'
}
{                                                                                                           10:08:57
  display: 'inline'
}
{                                                                                                           10:08:57
  position: 'relative'
}
{                                                                                                           10:08:57
  display: 'contents'
}
undefined                                                                                                   10:08:57
{                                                                                                           10:09:01
  display: 'table'
}
{                                                                                                           10:09:01
  display: 'inline'
}
{                                                                                                           10:09:01
  position: 'relative'
}
{                                                                                                           10:09:01
  display: 'contents'
}
undefined
```

**Comment by adam-nygate** [comment]
For some reason, it looks like `toString` is being passed to `extract()` which seems to be causing the issue. Although, I'm not sure where `toString` is originating from...

**Comment by adam-nygate** [comment]
Adding `blocklist: ['toString', 'valueOf', 'constructor', 'hasOwnProperty'],` to my windicss config block allows it to progress, but now I'm running into this error:
```
 ERROR  i.build is not a function                                                                           11:23:13

  at node_modules/@windicss/plugin-utils/dist/index.js:886:148
  at Array.map (<anonymous>)
  at compileStyleSheet (node_modules/@windicss/plugin-utils/dist/index.js:886:135)
  at StyleSheet2.build (node_modules/@windicss/plugin-utils/dist/index.js:944:14)
  at Object.generateCSS (node_modules/@windicss/plugin-utils/dist/index.js:44636:25)
  at async safeStartService (node_modules/windicss-webpack-plugin/dist/plugin.js:194:78)
  at async node_modules/windicss-webpack-plugin/dist/plugin.js:207:13
```

**Comment by adam-nygate** [comment]
It seems like this issue was caused because windi was scanning files outside of our src diretory, and setting `dirs: ['src']` does not seem to overide the dirs setting, but just appends to the array. 

Current fix is to exclude (using `scan.exclude` configuration) directoryies with files that cause this issue (for us it was AWS Amplify directories).
