### ISSUE TITLE
Cannot build some components, Webpack error ?

### ISSUE THREAD

**Issue by Tahul** [windicss/nuxt-windicss-module#21]
Hello and thank you for your work on this module @loonpwn 👍 

I'm trying to switch my project from @nuxtjs/tailwind to nuxt-windicss.

I've updated every of the imports from `tailwind/` to `windicss/`.

The build seem to be passing fine, but components are breaking it.

It seem to be related with Webpack, but this project cannot switch on nuxt-vite yet. 😞 

Here is a link to a reproduction: https://github.com/Tahul/nuxt-windicss-issue-repro

The stack trace:

```
ERROR  in ./components/atoms/CodeGroup.vue                                                                  friendly-errors 11:44:38
Module build failed (from ./node_modules/windicss-webpack-plugin/dist/loaders/transform-template.js):        friendly-errors 11:44:38
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.background [as bg] (/Users/tahul/Projets/nuxt/nuxtjs.com/node_modules/windicss/lib/index.js:7041:16)
    at extract (/Users/tahul/Projets/nuxt/nuxtjs.com/node_modules/windicss/lib/index.js:7638:42)
    at Processor.extract (/Users/tahul/Projets/nuxt/nuxtjs.com/node_modules/windicss/lib/index.js:8164:16)
    at _gStyle (/Users/tahul/Projets/nuxt/nuxtjs.com/node_modules/windicss/lib/index.js:8320:32)
    at /Users/tahul/Projets/nuxt/nuxtjs.com/node_modules/windicss/lib/index.js:8359:21
    at Array.forEach (<anonymous>)
    at Processor.compile (/Users/tahul/Projets/nuxt/nuxtjs.com/node_modules/windicss/lib/index.js:8355:13)
    at _loop_1 (/Users/tahul/Projets/nuxt/nuxtjs.com/node_modules/@windicss/plugin-utils/dist/index.js:2644:47)
    at CSSParser3.parse (/Users/tahul/Projets/nuxt/nuxtjs.com/node_modules/@windicss/plugin-utils/dist/index.js:2683:23)
    at _loop_1 (/Users/tahul/Projets/nuxt/nuxtjs.com/node_modules/@windicss/plugin-utils/dist/index.js:2631:32)
    at CSSParser3.parse (/Users/tahul/Projets/nuxt/nuxtjs.com/node_modules/@windicss/plugin-utils/dist/index.js:2683:23)
    at _loop_1 (/Users/tahul/Projets/nuxt/nuxtjs.com/node_modules/@windicss/plugin-utils/dist/index.js:2631:32)
    at CSSParser3.parse (/Users/tahul/Projets/nuxt/nuxtjs.com/node_modules/@windicss/plugin-utils/dist/index.js:2683:23)
    at _loop_1 (/Users/tahul/Projets/nuxt/nuxtjs.com/node_modules/@windicss/plugin-utils/dist/index.js:2631:32)
    at CSSParser3.parse (/Users/tahul/Projets/nuxt/nuxtjs.com/node_modules/@windicss/plugin-utils/dist/index.js:2683:23)
```

Thank you a lot for your help! 😃

**Comment by harlan-zw** [comment]
Thanks for the issue with the reproduction link @Tahul

 Looks like a bug in the main windicss repo caused by your configuration at  `plugins/nuxt-ui/presets.js`. I've created a PR to fix it

**Comment by harlan-zw** [comment]
Looks to be working now @Tahul :)
