### ISSUE TITLE
Nuxt build fails

### ISSUE THREAD

**Issue by itpropro** [windicss/nuxt-windicss-module#28]
Since updating to the most current version (`0.4.5`), the build fails:

![image](https://user-images.githubusercontent.com/15030951/111873585-41139e00-8991-11eb-9e92-94299aaae172.png)

```bash
 FATAL  Nuxt build error                                                                                         15:49:55

  at WebpackBundler.webpackCompile (node_modules\@nuxt\webpack\dist\webpack.js:2127:21)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async WebpackBundler.build (node_modules\@nuxt\webpack\dist\webpack.js:2076:5)
  at async Builder.build (node_modules\@nuxt\builder\dist\builder.js:327:5)
  at async Object.run (node_modules\@nuxt\cli\dist\cli-build.js:110:7)
  at async NuxtCommand.run (node_modules\@nuxt\cli\dist\cli-index.js:413:7)


   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

As also mentioned in #29, this leads to the following error when running `yarn dev`:

![image](https://user-images.githubusercontent.com/15030951/111880379-85139c80-89ab-11eb-8aab-148f743f1241.png)

```bash
 ERROR  Failed to compile with 2 errors                                                          friendly-errors 18:37:45


 ERROR  in ./.nuxt/views/app.template.html                                                       friendly-errors 18:37:45

Module parse failed: Unexpected token (1:0)                                                      friendly-errors 18:37:45
File was processed with these loaders:
 * ./node_modules/html-webpack-plugin/lib/loader.js
 * ./node_modules/windicss-webpack-plugin/dist/loaders/transform-template.js
You may need an additional loader to handle the result of these loaders.
> <!DOCTYPE html>
| <html {{ HTML_ATTRS }}>
|   <head {{ HEAD_ATTRS }}>
                                                                                                 friendly-errors 18:37:45
error                                                                                            friendly-errors 18:37:45
                                                                                                 friendly-errors 18:37:45
```

Steps to reproduce:

```bash
git clone https://github.com/itpropro/nuxt-windicss.git
cd nuxt-windicss
yarn
yarn build (or yarn dev)
```

**EDIT:**
Added the respective error when running `yarn dev` as mentioned in #29

**Comment by anyban** [comment]
+ i have it error too...

**Comment by itpropro** [comment]
It's since nuxt-windicss `0.4.5`, with `0.4.4` it works.

**Comment by ChangJoo-Park** [comment]
Same windicss-webpack-plugin version 0.2.5, I don't know why error after this commit https://github.com/windicss/nuxt-windicss-module/commit/3731253c5e177cfc50deb177a16ba8e599e98e60

**Comment by harlan-zw** [comment]
Hey guys, sorry about this one. Appreciate your help in trying to debug it and your patience.

The issue is sorted in [0.4.6](https://github.com/windicss/nuxt-windicss-module/releases/tag/0.4.6)

 I'll look to set up some automated tests so we can avoid breaking changes like this in the future as soon as I have some free time

**Comment by ChangJoo-Park** [comment]
Thanks @harlan-zw , It works with 0.4.6

**Comment by itpropro** [comment]
Thanks for the quick fix @harlan-zw :)
