### ISSUE TITLE
vercel deploy error

### ISSUE THREAD

**Issue by kukac7** [windicss/nuxt-windicss-module#86]
hi,

vercel deploy gets stuck, doesn't building.
if i turn off `nuxt-windicss` on `buildModules`, that's fine.

`vercel.json`:

```
{
	"version": 2,
	"builds": [
	{
			"src": "nuxt.config.js",
			"use": "@nuxtjs/vercel-builder"
		}
	]
}
```

vercel log:

```
15:43:04.099  	Cloning github.com/xy/xy (Branch: main, Commit: xy)
15:43:04.954  	Cloning completed: 854.628ms
15:43:04.978  	Analyzing source code...
15:43:04.983  	Warning: Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
15:43:06.184  	Installing build runtime...
15:43:09.035  	Build runtime installed: 2.850s
15:43:11.798  	Looking up build cache...
15:43:11.839  	Build cache not found
15:43:13.113  	[log] Running with @nuxt/vercel-builder version 0.21.2
15:43:13.113  	[log]  ----------------- Prepare build ----------------- 
15:43:13.113  	[log] Downloading files...
15:43:13.114  	[log] Working directory: /vercel/path0
15:43:13.116  	[log] Using yarn
15:43:13.143  	[info] Prepare build took: 30.081334 ms
15:43:13.143  	[log]  ----------------- Install devDependencies ----------------- 
15:43:13.490  	yarn install v1.22.10
15:43:13.508  	info No lockfile found.
15:43:13.512  	[1/5] Resolving packages...
15:43:14.171  	warning nuxt > @nuxt/babel-preset-app > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
15:43:16.487  	warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
15:43:16.491  	warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
15:43:17.209  	warning nuxt > @nuxt/webpack > webpack > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
15:43:17.212  	warning nuxt > @nuxt/webpack > webpack > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
15:43:18.022  	warning nuxt-vite > vite-plugin-vue2 > babel-preset-env > babel-plugin-transform-es2015-arrow-functions > babel-runtime > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
15:43:18.737  	[2/5] Fetching packages...
15:43:30.611  	info fsevents@2.3.2: The platform "linux" is incompatible with this module.
15:43:30.611  	info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
15:43:30.616  	info fsevents@1.2.13: The platform "linux" is incompatible with this module.
15:43:30.616  	info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
15:43:30.620  	[3/5] Linking dependencies...
15:43:30.622  	warning "nuxt > @nuxt/components@2.1.8" has unmet peer dependency "consola@*".
15:43:30.623  	warning "@nuxtjs/svg > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
15:43:30.624  	warning "@nuxtjs/svg > url-loader@4.1.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
15:43:30.627  	warning "@nuxtjs/svg > vue-svg-loader@0.16.0" has unmet peer dependency "vue-template-compiler@^2.0.0".
15:43:30.627  	warning "@nuxtjs/svg > raw-loader@4.0.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
15:43:30.627  	warning "@nuxtjs/svg > vue-svg-loader > svg-to-vue@0.7.0" has unmet peer dependency "vue-template-compiler@^2.0.0".
15:43:30.628  	warning "nuxt-vite > postcss-import@14.0.2" has unmet peer dependency "postcss@^8.0.0".
15:43:30.628  	warning "nuxt-vite > postcss-url@10.1.3" has unmet peer dependency "postcss@^8.0.0".
15:43:30.628  	warning "nuxt-windicss > vite-plugin-windicss@0.15.10" has unmet peer dependency "vite@^2.0.1".
15:43:38.715  	[4/5] Building fresh packages...
15:43:40.165  	[5/5] Cleaning modules...
15:43:41.780  	Done in 28.29s.
15:43:41.812  	[info] Install devDependencies took: 28668.791013 ms
15:43:41.813  	[log]  ----------------- Nuxt build ----------------- 
15:43:42.028  	[log] Running nuxt build --standalone --no-lock --config-file "nuxt.config.js" /vercel/path0
```

```
13:00:13.642 | [fatal] Nuxt build error
-- | --
13:00:13.642 | ERROR in ./virtual:windi.css (./node_modules_dev/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules_dev/postcss-loader/src??ref--3-oneOf-1-2!./node_modules_dev/windicss-webpack-plugin/dist/loaders/virtual-module.js!./virtual:windi.css)
13:00:13.642 | Module Error (from ./node_modules_dev/windicss-webpack-plugin/dist/loaders/virtual-module.js):
13:00:13.642 | (Emitted value instead of an instance of Error) [Windi CSS] Failed to generate CSS. Error: {
13:00:13.642 | "errno": -24,
13:00:13.642 | "code": "EMFILE",
13:00:13.642 | "syscall": "open",
13:00:13.642 | "path": "node_modules_dev/core-js/library/fn/parse-int.js"
13:00:13.642 | }
13:00:13.643 | @ ./virtual:windi.css 4:14-245
13:00:13.643 | @ ./node_modules_dev/nuxt-windicss/dist/template/windicss.js
13:00:13.643 | @ ./.nuxt/index.js
13:00:13.643 | @ ./.nuxt/client.js
13:00:13.643 | @ multi ./.nuxt/client.js
13:00:13.643 |  
13:00:13.643 | ERROR in ./virtual:windi.css (./node_modules_dev/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules_dev/postcss-loader/src??ref--3-oneOf-1-2!./node_modules_dev/windicss-webpack-plugin/dist/loaders/virtual-module.js!./virtual:windi.css)
13:00:13.643 | Module build failed (from ./node_modules_dev/windicss-webpack-plugin/dist/loaders/virtual-module.js):
13:00:13.643 | Error: EMFILE: too many open files, open 'node_modules_dev/core-js/library/fn/parse-int.js'
13:00:13.643 | @ ./virtual:windi.css 4:14-245
13:00:13.643 | @ ./node_modules_dev/nuxt-windicss/dist/template/windicss.js
13:00:13.643 | @ ./.nuxt/index.js
13:00:13.643 | @ ./.nuxt/client.js
13:00:13.643 | @ multi ./.nuxt/client.js
13:00:13.645 | ╭─────────────────────────────╮
13:00:13.645 | │                             │
13:00:13.645 | │   ✖ Nuxt Fatal Error        │
13:00:13.645 | │                             │
13:00:13.645 | │   Error: Nuxt build error   │
13:00:13.645 | │                             │
13:00:13.646 | ╰─────────────────────────────╯
13:00:13.688 | Error: Command failed with exit code 1: npx nuxt build --standalone --no-lock --config-file "nuxt.config.js" /vercel/path0
13:00:13.688 | at makeError (/vercel/b3a3026e4d524981/.build-utils/.builder/node_modules/execa/lib/error.js:59:11)
13:00:13.688 | at handlePromise (/vercel/b3a3026e4d524981/.build-utils/.builder/node_modules/execa/index.js:114:26)
13:00:13.688 | at processTicksAndRejections (internal/process/task_queues.js:93:5)
13:00:13.688 | at Object.build (/vercel/b3a3026e4d524981/.build-utils/.builder/node_modules/@nuxtjs/vercel-builder/lib/index.js:343:3)
13:00:13.688 | at buildStep (/var/task/webpack:/@zeit/api/scripts/build-container/src/utils/purpose-build.ts:166:1) {
13:00:13.688 | shortMessage: 'Command failed with exit code 1: npx nuxt build --standalone --no-lock --config-file "nuxt.config.js" /vercel/path0',
13:00:13.688 | command: 'npx nuxt build --standalone --no-lock --config-file "nuxt.config.js" /vercel/path0',
13:00:13.688 | exitCode: 1,
13:00:13.689 | signal: undefined,
13:00:13.689 | signalDescription: undefined,
13:00:13.689 | stdout: undefined,
13:00:13.689 | stderr: undefined,
13:00:13.689 | failed: true,
13:00:13.689 | timedOut: false,
13:00:13.689 | isCanceled: false,
13:00:13.689 | killed: false
13:00:13.689 | }
```

vecel default build and deploy settings.

**Comment by harlan-zw** [comment]
Hey @kukac7 

Would you mind sharing your windi config? It looks like it's trying to scan node_module files as part of the deployment

**Comment by kukac7** [comment]
hi @harlan-zw,

sure!
default config file.

```
module.exports = {
	theme: {
		container: {
			center: true,
			padding: {
				'DEFAULT': '1.75rem',
			},
		},
		fontFamily: {
			sans: ['Merriweather', 'serif'],
		},
	},
	variants: {},
	plugins: [],
}
```

**Comment by harlan-zw** [comment]
@kukac7 Have you made any configuration changes within the nuxt.config.js ?

The error is that there are too many files open so it means there's too much scanning going on. You can try v0.8.0 and maybe it will fix it, otherwise please share that config too

**Comment by kukac7** [comment]
nuxt.config.js

```
export default {
	server: {
		port: 4200
	},
	buildModules: [
		'nuxt-vite',
		'nuxt-windicss',
	],
}
```

if the vercel settings are not set manually (as in the picture above), you will issue this error:

```
12:58:55.746 | Error: No Output Directory named "dist" found after the Build completed. You can configure the Output Directory in your Project Settings. Learn More: https://vercel.link/missing-public-directory
-- | --
```

**Comment by provabeer** [comment]
hey @kukac7 did you find any solution for this?

**Comment by flavionn** [comment]
hey @kukac7 did you find any solution for this?

**Comment by kukac7** [comment]
@flavionn yes, look at the screenshot: https://github.com/windicss/nuxt-windicss-module/issues/86#issuecomment-846018114

**Comment by flavionn** [comment]
I'm facing the same problem but with ssr

the build completation with no errors in vercel only run when I remove nuxt-windicss from buildModules

if I don't remove, the build freezes on

```
[log] Running nuxt build --standalone --no-lock --config-file "nuxt.config.js" /vercel/path1
```

**nuxt-config.js**

```js
export default {

	// target
	target: 'server',

	// components
	components: true,

	// loading bar
	loading: { color: '#2ECC40' },

	// css
	css: [ '@/assets/global.scss' ],

	// head
	head: {
		title: process.env.APP_NAME,
		meta: [
			{ charset: 'utf-8' },
			{ name: 'viewport', content: 'width=device-width, initial-scale=1' },
			{ hid: 'description', name: 'description', content: process.env.APP_DESCRIPTION },
			{ hid: 'og:site_name', property: 'og:site_name', content: process.env.APP_NAME }
		],
		link: [
			{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
		]
	},

	// plugins
	plugins: [
	],

	// build modules
	buildModules: [
		'@nuxtjs/google-analytics',
		'@nuxtjs/google-fonts',
		'@nuxtjs/localforage',
		'nuxt-vite',
		'nuxt-windicss'
	],

	// modules
	modules: [
		'@nuxtjs/firebase'
	],

	// google analytics
	googleAnalytics: {
		id: process.env.GOOGLE_ANALYTICS_ID
	},

	// google fonts
	googleFonts: {
		families: {
			Inter: [400, 500, 600, 700]
		}
	},

	// firebase
	firebase: {
		config: {
			apiKey: process.env.FIREBASE_API_KEY,
			authDomain: process.env.FIREBASE_AUTH_DOMAIN,
			databaseURL: process.env.FIREBASE_DB_URL,
			projectId: process.env.FIREBASE_PROJECT_ID,
			storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
			messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
			appId: process.env.FIREBASE_APP_ID
		},
		services: {
			auth: true,
			firestore: true
		}
	}
}


```

**windi.config.js**

```js
module.exports = {
	theme: {
		extend: {
			fontFamily: {
				sans: 'Inter, ui-sans-serif, system-ui'
			}
		}
	}
}


```

**vercel.json**

```js
{
  "version": 2,
  "builds": [
    {
      "src": "nuxt.config.js",
      "use": "@nuxtjs/vercel-builder"
    }
  ]
}



```

**Comment by harlan-zw** [comment]
Hey @kukac7 and @flavionn 

Thanks for the reminder on this and apologies it's taken me so long to look into it.

My best bet is that because the vercel builder is renaming the `node_modules` folder to `node_modules_dev`, it is causing windi to scan all of your node modules. 

I've done an update to exclude the `node_modules_dev` folder in 1.0.4, can you try that version and let me know how it goes.

**Comment by nulltask** [comment]
@harlan-zw Thank you for your great works.

In my research, I found that the nuxt/vercel-builder package generates `node_modules_dev` and also `node_modules_prod` folders. I added `node_modules_prod` to excludes, so it will be fixed. Please review pull request #101.

**Comment by harlan-zw** [comment]
Sweet, thanks @nulltask :pray:

**Comment by flavionn** [comment]
hello, thanks for the changes. worked for me!

anyway, it's possible to apply this change (insert node_modules_dev and node_modules_prod) in version 0.7.5?

I have this problem #97 with any version above 0.7.5

**Comment by flavionn** [comment]
Hello!

I solved my problem (without updating 0.7.5) adding node_modules_dev and node_modules_prod in windicss > scan > exclude on nuxt.config.js - [https://windicss.org/integrations/nuxt.html#scanning](https://windicss.org/integrations/nuxt.html#scanning)

**nuxt.config.js**
```js
windicss: {
  scan: {
    exclude: [
      'node_modules',
      'node_modules_dev',
      'node_modules_prod'
    ]
  }
}
```

Everything is working when building my project on Vercel. No more freeze builds.

**Comment by harlan-zw** [comment]
@flavionn That is perfectly fine to have it like that.

Will close this one for now

**Comment by flavionn** [comment]
Hello! Thanks for all support.

I did one more test and found that when I use the nuxt vercel builder and the nuxt windicss module version 1.0.6, with automatic deployment on Vercel using the GitHub repository it runs the build (does not freeze) but returns "nuxt internal server error" when I try to access the application.

I'm not using any custom configuration in windi.config.js nor in nuxt.config.js
